services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=precos
      - DB_USER=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=catalogo
    ports:
      - "3306:3306"
    volumes:
      - ./catalogo.sql:/docker-entrypoint-initdb.d/catalogo.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
